Добавляет разметку главной страницы Седона
htmlacademy-htmlcss/548411-sedona-33 pull request #2
Opened 2022-01-24 11:38 UTC by AntoninaManzhela

2022-01-24 15:52 UTC, Dima-Dim requested changes

2022-01-24 15:52 UTC, Dima-Dim commented on index.html
> +          <P class="advantages-description">Настоящий городок</P>
Почему `P`? :)

2022-01-24 15:52 UTC, Dima-Dim commented on index.html
> +          <h3 class="visually-hidden">№1</h3>
Зачем нам это скрытый заголовок? Если в тексте `№1` есть действительно что-то важное, то ниже он есть не скрытый.

2022-01-24 15:52 UTC, Dima-Dim commented on index.html
> +                <img class="icon-1" src="#">
https://up.htmlacademy.ru/htmlcss/33/module/2/item/19

2022-01-24 15:52 UTC, Dima-Dim commented on index.html
> +      <a class="button hotel-search-button" href="catalog.html">ПОИСК ГОСТИНИЦЫ В седоне</a>
Тексты в разметке пишим как в обычных предложениях.

2022-01-25 08:26 UTC, AntoninaManzhela commented on index.html
> +          <P class="advantages-description">Настоящий городок</P>
На макете Седоны этот текст отмечен как обычная фраза. Но по смыслу это должен быть заголовок. Здесь подойдет тег h4?
![Снимок](https://user-images.githubusercontent.com/93258577/150939077-20b3cd34-cb3d-49fb-91d3-3700cf62bde5.PNG)

2022-01-25 12:13 UTC, Dima-Dim commented on index.html
> +          <P class="advantages-description">Настоящий городок</P>
Здесь вопрос про регистр буквы, почему она большая, а не маленькая :)

2022-01-26 05:53 UTC, Dima-Dim commented on index.html
> +              <backround-image class="favorites" src="#"></backround-image>
Не нужно выдумывать :) Изображения пока не будет в разметке ни в каком виде, ничего страшного.

2022-01-26 05:53 UTC, merged

2022-01-26 06:56 UTC, AntoninaManzhela commented on index.html
> +              <backround-image class="favorites" src="#"></backround-image>
Поняла, спасибо :)