Добавляет контентные изображения в разметку
htmlacademy-htmlcss/548411-sedona-33 pull request #4
Opened 2022-02-02 10:00 UTC by AntoninaManzhela

2022-02-02 11:32 UTC, Dima-Dim requested changes
images/backgrounds/catalog-background 1.jpg и подобные - https://up.htmlacademy.ru/htmlcss/33/criteries#PROJ-031
"... без пробелов ...".

2022-02-02 11:32 UTC, Dima-Dim commented on index.html
> +              <img class="favorites" src="#">
Не надо :) Займёшься этим после раздела про декоративные элементы.

2022-02-02 11:43 UTC, AntoninaManzhela commented on index.html
> +              <img class="favorites" src="#">
Тогда пока удалю, чтобы не отвлекало

2022-02-03 07:53 UTC, Dima-Dim approved these changes

2022-02-03 07:54 UTC, merged